### PR TITLE
Functional programming and performance upgrade

### PR DESCRIPTION
**Pull request by rafakato**
All new and old tests passing, take a look if there is anything not working well.

### CODE REVIEW

**Comment by wankdanker** [comment]
I'm so psyched about this. Any benchmarks? Will probably merge this later tonight or tomorrow.

**Comment by rafakato** [comment]
I'll try to make some benchmarks. But if there is no much difference I
think it become easier to read, what do you think?

On Thu, 23 Jul 2015 19:32 Dan VerWeire <notifications@github.com> wrote:

> I'm so psyched about this. Any benchmarks? Will probably merge this later
> tonight or tomorrow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wankdanker/node-object-mapper/pull/9#issuecomment-124255975>
> .
>
-- 
--
Rafael Kato

**Comment by wankdanker** [comment]
:+1: removing lodash.

**Comment by wankdanker** [comment]
Yes, it is much more readable and more organized. Smarter processing of keys without using arrays, nice. I bet it's probably fast too.

**Comment by wankdanker** [comment]
I merged your work into my master branch and added a failing test. I think that we should be able to have the from object be an array so you can have a map like:

```js
var obj = [
  { a : 'a1', b : 'b1' }
  , { a : 'a2', b : 'b2' }
];
 var map = {
 '[].a' : '[].c'
 , '[].b' : '[].d'
};
 var expect = [
  { c : 'a1', d : 'b1' }
  , { c : 'a2', d : 'b2' }
];

var result = om(obj, map);
```

What do you think about that? Could you make that work?

**Comment by rafakato** [comment]
I'll try solve it later

**Comment by wankdanker** [comment]
Also, since this is a major rewrite and you have probably internalized the code more than me, I'm going to add you as a maintainer here and npm.

Thank you for your work.

**Comment by rafakato** [comment]
Nice, thank you

**Pull request merged**
